// src/components/VideoList.tsx
import { useEffect, useState } from "react";
import axios from "axios";
import ReactTimeago from "react-timeago";

const VideoList = () => {
  const [youtubeLists, setYoutubeLists] = useState<any[]>([]);

  useEffect(() => {
    _loadYoutubeLists();
  }, []);

  const _loadYoutubeLists = async () => {
    const response = await axios.get("http://localhost:8080/api/v1/list/lists");
    setYoutubeLists(response.data.content);
    console.log(response.data.content);
    console.log(youtubeLists);
  };

  return (
    <main className=".container-fluid flex flex-wrap">
      {youtubeLists.map((youtubeList) => {
        return (
          <div key={youtubeList.playListId} className="relative w-80 p-2">
            <img
              className="h-[180px] w-[320px] rounded-xl object-fill"
              src={youtubeList.thumbnail}
              alt={youtubeList.title}
            />
            <div>
              <b>{youtubeList.title}</b>
              <div>{youtubeList.channelTitle}</div>
              <ReactTimeago date={youtubeList.publishedAt} />
            </div>
          </div>
        );
      })}
    </main>
  );
};

export default VideoList;

// src/components/VideoList.vue
<script setup lang="ts">
import { ref, onMounted } from "vue";
import axios from "axios";
import {
  HandThumbUpIcon,
  EyeIcon,
  ListBulletIcon,
} from "@heroicons/vue/16/solid";

const videos = ref([]);
const youtubeLists = ref<any>([]);

onMounted(async () => {
  const response = await axios.get("http://localhost:8080/api/v1/video/videos");
  videos.value = response.data.content;
  const youtubeResponse = await axios.get(
    "http://localhost:8080/api/v1/list/lists",
  );
  youtubeLists.value = youtubeResponse.data.content;
});

const numberToTIme = (number: number) => {
  const hours = Math.floor(number / 3600);
  const minutes = Math.floor((number % 3600) / 60);
  const seconds = Math.floor(number % 60);

  return `${hours ? `${hours}:` : ""}${minutes}:${seconds}`;
};
</script>

<template>
  <div>
    <div class="flex flex-wrap space-x-2">
      <router-link
        :to="{ name: 'watch', params: { uuid: video.uuid } }"
        v-for="video in videos"
        :key="video.id"
        class="w-80 cursor-pointer"
      >
        <div class="relative w-80">
          <img
            class="h-[180px] w-[320px] rounded-xl object-fill"
            :src="`data:image/png;base64,${video.thumbnail}`"
            alt="video thumbnail"
          />
          <div
            class="absolute bottom-2 right-2 rounded-md bg-slate-600 bg-opacity-50 px-1 text-sm text-white"
          >
            {{ numberToTIme(video.videoInfo.duration) }}
          </div>
        </div>
        <div class="flex flex-col">
          <div class="text-right text-xs">
            <HandThumbUpIcon class="inline w-4" /> {{ video.like }} &nbsp;
            <EyeIcon class="inline w-4" /> {{ video.hit }}
          </div>
          <div class="font-bold">{{ video.title }}</div>
          <div>{{ video.author }}</div>
          <timeago class="text-sm" :datetime="video.uploadedAt" />
        </div>
      </router-link>
    </div>
    <div class="py-2 text-lg font-extrabold text-red-500">youtube</div>
    <div class="flex flex-wrap space-x-2">
      <router-link
        :to="{
          name: 'youtubeListItem',
          params: { playListId: youtubeList.playListId },
        }"
        v-for="youtubeList in youtubeLists"
        :key="youtubeList.playListId"
        class="h-80 w-80 cursor-pointer"
      >
        <div class="relative w-80">
          <img
            class="h-[180px] w-[320px] rounded-xl object-fill"
            :src="youtubeList.thumbnail"
            alt="video thumbnail"
          />
        </div>
        <div class="flex flex-col">
          <div class="text-right text-xs">
            <HandThumbUpIcon class="inline w-4" /> 0 &nbsp;
            <EyeIcon class="inline w-4" /> 0 &nbsp;
            <ListBulletIcon class="inline w-4" />
            {{ youtubeList.contentDetails.itemCount }}
          </div>
          <div class="font-bold">{{ youtubeList.title }}</div>
          <div>{{ youtubeList.channelTitle }}</div>
          <timeago class="text-sm" :datetime="youtubeList.publishedAt" />
        </div>
      </router-link>
    </div>
  </div>
</template>
