// src/components/YoutubeVideoCard.vue
<script setup lang="ts">
import { PlayListItem } from "../types";

interface Props {
  index: number;
  playListItem: PlayListItem;
}

// Props를 정의합니다
const props = defineProps<Props>();
</script>

<template>
  <div class="flex cursor-pointer hover:bg-slate-200">
    <div class="w-8 flex-none self-center text-center text-sm">
      {{ props.index }}
    </div>
    <img
      class="h-[56.25px] w-[100px] flex-none p-0.5"
      :src="props.playListItem.thumbnail"
      :alt="props.playListItem.title"
    />
    <div class="flex shrink flex-col">
      <p class="line-clamp-2">{{ props.playListItem.title }}</p>
      <p class="text-xs text-gray-500">
        {{ props.playListItem.videoOwnerChannelTitle }}
      </p>
    </div>
  </div>
</template>

// src/components/YoutubeVideoCard.tsx
import { PlayListItem } from "../types/PlayLists";

interface YoutubeVideoCardProps {
  index: number;
  playListItem: PlayListItem;
}

const YoutubeVideoCard = ({ index, playListItem }: YoutubeVideoCardProps) => {
  return (
    <div className="flex cursor-pointer hover:bg-slate-200">
      <div className="w-8 flex-none self-center text-center text-sm">
        {index}
      </div>
      <img
        className="h-[56.25px] w-[100px] flex-none p-0.5"
        src={playListItem.thumbnail}
        alt={playListItem.title}
      />
      <div className="flex shrink flex-col">
        <p className="line-clamp-2">{playListItem.title}</p>
        <p className="text-xs text-gray-500">
          {playListItem.videoOwnerChannelTitle}
        </p>
      </div>
    </div>
  );
};

export default YoutubeVideoCard;
